-- MySQL Script generated by MySQL Workbench
-- Sun May 21 19:24:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_ejemplo_innova
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_ejemplo_innova` ;

-- -----------------------------------------------------
-- Schema bd_ejemplo_innova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ejemplo_innova` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_ejemplo_innova` ;

-- -----------------------------------------------------
-- Table `bd_ejemplo_innova`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ejemplo_innova`.`persona` (
  `DNI` INT NULL DEFAULT NULL,
  `Nombre` VARCHAR(30) NULL DEFAULT NULL,
  `Direccion` VARCHAR(30) NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
